Repository efonsecab/FairPlayTube, pull requests merged in 2021-06, with the labels that each got.

#54 Adding keywords page.
  src/FairPlayTubeSln/FairPlayTube.Client/ClientServices/VideoClientService.cs
  src/FairPlayTubeSln/FairPlayTube.Client/Pages/Index.razor
  src/FairPlayTubeSln/FairPlayTube.Client/Pages/Index.razor.cs
  src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Videos/Keywords.razor
  src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Videos/Keywords.razor.cs
  src/FairPlayTubeSln/FairPlayTube.Client/Shared/NavMenu.razor
  src/FairPlayTubeSln/FairPlayTube.Common/Global/Constants.cs
  src/FairPlayTubeSln/FairPlayTube.Components/FairPlayTube.Components.csproj
  src/FairPlayTubeSln/FairPlayTube.Components/Videos/VideoList.razor
  src/FairPlayTubeSln/FairPlayTube.Components/Videos/VideoList.razor.cs
  src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs
  src/FairPlayTubeSln/FairPlayTube/Controllers/VideoController.cs
Labels: enhancement

#18 initial configuration for automated test
  src/FairPlayTubeSln/FairPlayTube.Tests/Controllers/AzureVideoIndexerControllerTests.cs
  src/FairPlayTubeSln/FairPlayTube.Tests/Controllers/UserControllerTests.cs
  src/FairPlayTubeSln/FairPlayTube.Tests/Controllers/UserProfileControllerTests.cs
  src/FairPlayTubeSln/FairPlayTube.Tests/Controllers/VideoControllerTests.cs
  src/FairPlayTubeSln/FairPlayTube.Tests/FairPlayTube.Tests.csproj
  src/FairPlayTubeSln/FairPlayTube.Tests/TestsBase.cs
  src/FairPlayTubeSln/FairPlayTubeSln.sln
Labels: enhancement

#68 Create Table: Brand Video
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Data/FairplaytubeDatabaseContext.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/Brand.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/BrandVideo.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/VideoInfo.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/efpt.config.json
  src/FairPlayTubeSln/FairPlayTube.Database/FairPlayTube.Database.refactorlog
  src/FairPlayTubeSln/FairPlayTube.Database/FairPlayTube.Database.sqlproj
  src/FairPlayTubeSln/FairPlayTube.Database/dbo/Tables/Brand.sql
  src/FairPlayTubeSln/FairPlayTube.Database/dbo/Tables/BrandVideo.sql
Labels: good first issue

#69 Create Table: UserFeedback
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Data/FairplaytubeDatabaseContext.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/ApplicationUser.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/UserFeedback.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/efpt.config.json
  src/FairPlayTubeSln/FairPlayTube.Database/FairPlayTube.Database.sqlproj
  src/FairPlayTubeSln/FairPlayTube.Database/dbo/Tables/UserFeedback.sql
Labels: enhancement, good first issue

#70 Add Column AvailableFunds to ApplicationUser Table
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/ApplicationUser.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/efpt.config.json
  src/FairPlayTubeSln/FairPlayTube.Database/dbo/Tables/ApplicationUser.sql
Labels: good first issue

#72 Adding base for supporting SignalR
  src/FairPlayTubeSln/FairPlayTube.Client/CustomComponents/SignalR/NotificationHub.razor
  src/FairPlayTubeSln/FairPlayTube.Client/CustomComponents/SignalR/NotificationHub.razor.cs
  src/FairPlayTubeSln/FairPlayTube.Client/FairPlayTube.Client.csproj
  src/FairPlayTubeSln/FairPlayTube.Client/Shared/MainLayout.razor
  src/FairPlayTubeSln/FairPlayTube.Client/Shared/NavMenu.razor
  src/FairPlayTubeSln/FairPlayTube.Common/Global/Constants.cs
  src/FairPlayTubeSln/FairPlayTube.Models/Notifications/NotificationModel.cs
  src/FairPlayTubeSln/FairPlayTube/Controllers/AzureVideoIndexerController.cs
  src/FairPlayTubeSln/FairPlayTube/Notifications/Hubs/INotificationHub.cs
  src/FairPlayTubeSln/FairPlayTube/Notifications/Hubs/NotificationHub.cs
  src/FairPlayTubeSln/FairPlayTube/Startup.cs
Labels: enhancement

#75 Implementing notifications to video owners when videos have finished …
  src/FairPlayTubeSln/FairPlayTube.Client/CustomComponents/SignalR/NotificationHub.razor
  src/FairPlayTubeSln/FairPlayTube.Client/CustomComponents/SignalR/NotificationHub.razor.cs
  src/FairPlayTubeSln/FairPlayTube.Client/FairPlayTube.Client.csproj
  src/FairPlayTubeSln/FairPlayTube.Client/Pages/Authentication.razor
  src/FairPlayTubeSln/FairPlayTube.Client/Shared/MainLayout.razor
  src/FairPlayTubeSln/FairPlayTube.Notifications/FairPlayTube.Notifications.csproj
  src/FairPlayTubeSln/FairPlayTube.Notifications/Hubs/INotificationHub.cs
  src/FairPlayTubeSln/FairPlayTube.Notifications/Hubs/NotificationHub.cs
  src/FairPlayTubeSln/FairPlayTube.Services/BackgroundServices/VideoIndexStatusService.cs
  src/FairPlayTubeSln/FairPlayTube.Services/FairPlayTube.Services.csproj
  src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs
  src/FairPlayTubeSln/FairPlayTube/FairPlayTube.csproj
  src/FairPlayTubeSln/FairPlayTubeSln.sln
Labels: enhancement

#77 Create Table: UserFollower
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Data/FairplaytubeDatabaseContext.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/ApplicationUser.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/UserFollower.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/UserFollower.partial.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/efpt.config.json
  src/FairPlayTubeSln/FairPlayTube.Database/FairPlayTube.Database.sqlproj
  src/FairPlayTubeSln/FairPlayTube.Database/dbo/Tables/UserFollower.sql
Labels: enhancement

#78 Create Table: UserInvitation
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Data/FairplaytubeDatabaseContext.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/ApplicationUser.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/UserInvitation.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/UserInvitation.partial.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/efpt.config.json
  src/FairPlayTubeSln/FairPlayTube.Database/FairPlayTube.Database.sqlproj
  src/FairPlayTubeSln/FairPlayTube.Database/dbo/Tables/UserInvitation.sql
Labels: enhancement, good first issue

#76 Create Table: UserVideoRating
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Data/FairplaytubeDatabaseContext.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/ApplicationUser.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/UserVideoRating.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/UserVideoRating.partial.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/VideoInfo.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/efpt.config.json
  src/FairPlayTubeSln/FairPlayTube.Database/FairPlayTube.Database.sqlproj
  src/FairPlayTubeSln/FairPlayTube.Database/dbo/Tables/UserVideoRating.sql
Labels: enhancement, good first issue

#88 UsersPage Added
  src/FairPlayTubeSln/FairPlayTube.Client/ClientServices/UserProfileClientService.cs
  src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/List.razor
  src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/List.razor.cs
  src/FairPlayTubeSln/FairPlayTube.Client/Shared/NavMenu.razor
  src/FairPlayTubeSln/FairPlayTube.Common/Global/Constants.cs
  src/FairPlayTubeSln/FairPlayTubeSln.sln
Labels: enhancement

#89 SendMessage Endpoint Created
  src/FairPlayTubeSln/FairPlayTube.Models/UserMessage/UserMessageModel.cs
  src/FairPlayTubeSln/FairPlayTube/Controllers/UserController.cs
Labels: enhancement

#93 Setting default sorting to newest videos first
  src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs
Labels: enhancement
