Repository efonsecab/FairPlayTube, pull requests merged in 2021-07, with the labels that each got.

#102 Table VideoIndexingTransaction Created
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Data/FairplaytubeDatabaseContext.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/VideoIndexingTransaction.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/VideoIndexingTransaction.partial.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/VideoInfo.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/efpt.config.json
  src/FairPlayTubeSln/FairPlayTube.Database/dbo/Tables/VideoIndexingTransaction.sql
Labels: enhancement

#103 Table VIdeoIndexingCost Created
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Data/FairplaytubeDatabaseContext.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/VideoIndexingCost.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/VideoIndexingCost.partial.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/efpt.config.json
  src/FairPlayTubeSln/FairPlayTube.Database/FairPlayTube.Database.sqlproj
  src/FairPlayTubeSln/FairPlayTube.Database/dbo/Tables/VideoIndexingCost.sql
Labels: enhancement

#104 Create VideoIndexingTransaction Record on Successfull Video Indexation
  src/FairPlayTubeSln/FairPlayTube.Services/BackgroundServices/VideoIndexStatusService.cs
  src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs
Labels: enhancement

#105 VideoIndexingMargin Table Created
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Data/FairplaytubeDatabaseContext.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/VideoIndexingMargin.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/VideoIndexingMargin.partial.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/efpt.config.json
  src/FairPlayTubeSln/FairPlayTube.Database/FairPlayTube.Database.sqlproj
  src/FairPlayTubeSln/FairPlayTube.Database/dbo/Tables/VideoIndexingMargin.sql
Labels: enhancement

#107 Adding mailchimp popup
  src/FairPlayTubeSln/FairPlayTube.Client/wwwroot/index.html
Labels: enhancement

#113 Enabling fields to set and display a video's price
  src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Videos/Upload.razor
  src/FairPlayTubeSln/FairPlayTube.Client/_Imports.razor
  src/FairPlayTubeSln/FairPlayTube.Common/Global/Constants.cs
  src/FairPlayTubeSln/FairPlayTube.Components/FairPlayTube.Components.csproj
  src/FairPlayTubeSln/FairPlayTube.Components/Videos/VideoList.razor
  src/FairPlayTubeSln/FairPlayTube.Components/_Imports.razor
  src/FairPlayTubeSln/FairPlayTube.Models/FairPlayTube.Models.csproj
  src/FairPlayTubeSln/FairPlayTube.Models/Video/UploadVideoModel.cs
  src/FairPlayTubeSln/FairPlayTube.Models/Video/VideoInfoModel.cs
  src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs
Labels: enhancement

#115 Adding endpoint to allow updating owned video
  src/FairPlayTubeSln/FairPlayTube.Models/Video/UpdateVideoModel.cs
  src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs
  src/FairPlayTubeSln/FairPlayTube/Controllers/VideoController.cs
Labels: enhancement

#124 Adding BuyVideoAccess icon
  src/FairPlayTubeSln/FairPlayTube.Components/Videos/VideoList.razor
Labels: enhancement

#131 Converting menu items into icons.
  src/FairPlayTubeSln/FairPlayTube.Client/Shared/MainLayout.razor.css
  src/FairPlayTubeSln/FairPlayTube.Client/Shared/NavMenu.razor
  src/FairPlayTubeSln/FairPlayTube.Client/Shared/NavMenu.razor.css
Labels: enhancement

#133 Moving Client Services to a class library.
  src/FairPlayTubeSln/FairPlayTube.Client/CustomClaims/CustomAccountClaimsPrincipalFactory.cs
  src/FairPlayTubeSln/FairPlayTube.Client/CustomComponents/Paypal/PaypalCheckout.razor.cs
  src/FairPlayTubeSln/FairPlayTube.Client/CustomComponents/Videos/EditVideo.razor.cs
  src/FairPlayTubeSln/FairPlayTube.Client/FairPlayTube.Client.csproj
  src/FairPlayTubeSln/FairPlayTube.Client/Pages/Index.razor.cs
  src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/List.razor.cs
  src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Profile/Monetization.razor.cs
  src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Profile/MyFunds.razor.cs
  src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Videos/Details.razor.cs
  src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Videos/Keywords.razor.cs
  src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Videos/MyVideos.razor
  src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Videos/MyVideos.razor.cs
  src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Videos/Upload.razor.cs
  src/FairPlayTubeSln/FairPlayTube.Client/Program.cs
  src/FairPlayTubeSln/FairPlayTube.ClientServices/FairPlayTube.ClientServices.csproj
  src/FairPlayTubeSln/FairPlayTube.ClientServices/HttpClientService.cs
  src/FairPlayTubeSln/FairPlayTube.ClientServices/UserProfileClientService.cs
  src/FairPlayTubeSln/FairPlayTube.ClientServices/VideoClientService.cs
  src/FairPlayTubeSln/FairPlayTube.Components/FairPlayTube.Components.csproj
  src/FairPlayTubeSln/FairPlayTube.Components/Videos/VideoList.razor
  src/FairPlayTubeSln/FairPlayTube.Components/Videos/VideoList.razor.cs
  src/FairPlayTubeSln/FairPlayTubeSln.sln
Labels: enhancement

#135 Adding Visitor Tracking table
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Data/FairplaytubeDatabaseContext.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/ApplicationUser.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/VisitorTracking.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/efpt.config.json
  src/FairPlayTubeSln/FairPlayTube.Database/FairPlayTube.Database.refactorlog
  src/FairPlayTubeSln/FairPlayTube.Database/FairPlayTube.Database.sqlproj
  src/FairPlayTubeSln/FairPlayTube.Database/dbo/Tables/VisitorTracking.sql
Labels: enhancement

#137 Adding Visitor Tracking
  src/FairPlayTubeSln/FairPlayTube.Client/CustomComponents/Tracking/VisitorTracking.razor
  src/FairPlayTubeSln/FairPlayTube.Client/CustomComponents/Tracking/VisitorTracking.razor.cs
  src/FairPlayTubeSln/FairPlayTube.Client/Pages/Index.razor
  src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/List.razor
  src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Profile/Monetization.razor
  src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Profile/MyFunds.razor
  src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Videos/Details.razor
  src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Videos/Keywords.razor
  src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Videos/MyVideos.razor
  src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Videos/Upload.razor
  src/FairPlayTubeSln/FairPlayTube.Client/Program.cs
  src/FairPlayTubeSln/FairPlayTube.Client/_Imports.razor
  src/FairPlayTubeSln/FairPlayTube.ClientServices/VisitorTrackingClientService.cs
  src/FairPlayTubeSln/FairPlayTube.Common/Global/Constants.cs
  src/FairPlayTubeSln/FairPlayTube.Common/Providers/IpAddressProvider.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Data/FairplaytubeDatabaseContext.partial.cs
  src/FairPlayTubeSln/FairPlayTube.Models/VisitorTracking/VisitorTrackingModel.cs
  src/FairPlayTubeSln/FairPlayTube.Services/FairPlayTube.Services.csproj
  src/FairPlayTubeSln/FairPlayTube.Services/VisitorTrackingService.cs
  src/FairPlayTubeSln/FairPlayTube/Controllers/VisitorTrackingController.cs
  src/FairPlayTubeSln/FairPlayTube/Startup.cs
  src/FairPlayTubeSln/FairPlayTubeSln.sln
Labels: enhancement

#138 Adding custom video indexer mediator script
  src/FairPlayTubeSln/FairPlayTube.Client/wwwroot/Index.Development.html
  src/FairPlayTubeSln/FairPlayTube.Client/wwwroot/index.html
  src/FairPlayTubeSln/FairPlayTube.Client/wwwroot/js/azure/video-indexer/vb.widgets.mediator.js
Labels: bug, help wanted

#140 Adding the "GetMyPendingVideosQueue" endpoint
  src/FairPlayTubeSln/FairPlayTube.Models/Video/VideoStatusModel.cs
  src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs
  src/FairPlayTubeSln/FairPlayTube/Controllers/VideoController.cs
Labels: enhancement

#142 Adding page to check pending videos status
  src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Videos/MyPendingVideosStatus.razor
  src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Videos/MyPendingVideosStatus.razor.cs
  src/FairPlayTubeSln/FairPlayTube.Client/Shared/NavMenu.razor
  src/FairPlayTubeSln/FairPlayTube.ClientServices/VideoClientService.cs
  src/FairPlayTubeSln/FairPlayTube.Common/Global/Constants.cs
  src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs
Labels: enhancement

#146 Adding the VideoJob table
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Data/FairplaytubeDatabaseContext.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/VideoInfo.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/VideoJob.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/efpt.config.json
  src/FairPlayTubeSln/FairPlayTube.Database/FairPlayTube.Database.refactorlog
  src/FairPlayTubeSln/FairPlayTube.Database/FairPlayTube.Database.sqlproj
  src/FairPlayTubeSln/FairPlayTube.Database/dbo/Tables/VideoJob.sql
Labels: enhancement

#148 Creating the "AddVideoJobAsync" method
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/VideoJob.partial.cs
  src/FairPlayTubeSln/FairPlayTube.Models/Video/VideoJobModel.cs
  src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs
Labels: enhancement

#150 Adding the AddVideoJob endpoint
  src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs
  src/FairPlayTubeSln/FairPlayTube/Controllers/VideoController.cs
Labels: enhancement

#152 Adding the number of Available Jobs
  src/FairPlayTubeSln/FairPlayTube.Components/Videos/VideoList.razor
  src/FairPlayTubeSln/FairPlayTube.Models/Video/VideoInfoModel.cs
  src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs
  src/FairPlayTubeSln/FairPlayTube/AutoMapperProfiles/GlobalMappingProfile.cs
Labels: enhancement

#154 Enhancing the "Available Jobs" tooltip message
  src/FairPlayTubeSln/FairPlayTube.Components/Videos/VideoList.razor
  src/FairPlayTubeSln/FairPlayTube.Models/Video/VideoInfoModel.cs
  src/FairPlayTubeSln/FairPlayTube/AutoMapperProfiles/GlobalMappingProfile.cs
Labels: enhancement

#144 VideoIndexingTransaction IndexingCost Column & Service
  src/FairPlayTubeSln/FairPlayTube.DataAccess/FairPlayTube.DataAccess.csproj
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/VideoIndexingCost.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/VideoIndexingMargin.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/VideoIndexingTransaction.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/efpt.config.json
  src/FairPlayTubeSln/FairPlayTube.Database/dbo/Tables/VideoIndexingCost.sql
  src/FairPlayTubeSln/FairPlayTube.Database/dbo/Tables/VideoIndexingMargin.sql
  src/FairPlayTubeSln/FairPlayTube.Database/dbo/Tables/VideoIndexingTransaction.sql
  src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs
Labels: enhancement

#160 Fix menu black spaces
  src/FairPlayTubeSln/FairPlayTube.Client/Shared/MainLayout.razor.css
  src/FairPlayTubeSln/FairPlayTube.SystemConfigurator/Shared/MainLayout.razor.css
Labels: bug

#162 Adding the BuyVideoAccessAsync method to VideoClientService
  src/FairPlayTubeSln/FairPlayTube.ClientServices/VideoClientService.cs
Labels: enhancement

#174 Adding the "GetAllPersonsAsync" method to the VideoService class
  src/FairPlayTubeSln/FairPlayTube.Models/Persons/PersonModel.cs
  src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs
Labels: enhancement

#176 Adding the person table
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Data/FairplaytubeDatabaseContext.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/Person.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/Person.partial.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/efpt.config.json
  src/FairPlayTubeSln/FairPlayTube.Database/FairPlayTube.Database.refactorlog
  src/FairPlayTubeSln/FairPlayTube.Database/FairPlayTube.Database.sqlproj
  src/FairPlayTubeSln/FairPlayTube.Database/dbo/Tables/Person.sql
Labels: enhancement

#178 Adding logic to persist persons and sample faces picture
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/Person.cs
  src/FairPlayTubeSln/FairPlayTube.Database/dbo/Tables/Person.sql
  src/FairPlayTubeSln/FairPlayTube.Models/Persons/PersonModel.cs
  src/FairPlayTubeSln/FairPlayTube.Services/BackgroundServices/VideoIndexStatusService.cs
  src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs
Labels: enhancement

#180 Adding the "GetPersistedPersonsAsync" method
  src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs
Labels: enhancement

#182 Adding GetPersons endpoint
  src/FairPlayTubeSln/FairPlayTube.Models/Persons/PersonModel.cs
  src/FairPlayTubeSln/FairPlayTube/AutoMapperProfiles/GlobalMappingProfile.cs
  src/FairPlayTubeSln/FairPlayTube/Controllers/VideoController.cs
Labels: enhancement

#184 Adding GetPersons Client and persons page
  src/FairPlayTubeSln/FairPlayTube.Client/FairPlayTube.Client.csproj
  src/FairPlayTubeSln/FairPlayTube.Client/Pages/Persons.razor
  src/FairPlayTubeSln/FairPlayTube.Client/Pages/Persons.razor.cs
  src/FairPlayTubeSln/FairPlayTube.Client/Shared/NavMenu.razor
  src/FairPlayTubeSln/FairPlayTube.ClientServices/VideoClientService.cs
  src/FairPlayTubeSln/FairPlayTube.Common/Global/Constants.cs
  src/FairPlayTubeSln/FairPlayTube/Controllers/VideoController.cs
Labels: enhancement

#191 Setting projects to treat warnings as errors
  src/FairPlayTubeSln/FairPlayTube.Client/FairPlayTube.Client.csproj
  src/FairPlayTubeSln/FairPlayTube.Client/Pages/Index.razor
  src/FairPlayTubeSln/FairPlayTube.ClientServices/FairPlayTube.ClientServices.csproj
  src/FairPlayTubeSln/FairPlayTube.Common/FairPlayTube.Common.csproj
  src/FairPlayTubeSln/FairPlayTube.Components/FairPlayTube.Components.csproj
  src/FairPlayTubeSln/FairPlayTube.DataAccess/FairPlayTube.DataAccess.csproj
  src/FairPlayTubeSln/FairPlayTube.Database/FairPlayTube.Database.sqlproj
  src/FairPlayTubeSln/FairPlayTube.Models/FairPlayTube.Models.csproj
  src/FairPlayTubeSln/FairPlayTube.Notifications/FairPlayTube.Notifications.csproj
  src/FairPlayTubeSln/FairPlayTube.Services/FairPlayTube.Services.csproj
  src/FairPlayTubeSln/FairPlayTube.SystemConfigurator/FairPlayTube.SystemConfigurator.csproj
  src/FairPlayTubeSln/FairPlayTube.Tests/Controllers/VideoControllerTests.cs
  src/FairPlayTubeSln/FairPlayTube.Tests/FairPlayTube.Tests.csproj
  src/FairPlayTubeSln/FairPlayTube.Tests/TestsBase.cs
  src/FairPlayTubeSln/FairPlayTube.VideoIndexer/FairPlayTube.VideoIndexer.csproj
  src/FairPlayTubeSln/FairPlayTube/FairPlayTube.csproj
Labels: enhancement

#193 Enabling Xml Documentation for the Models project
  src/FairPlayTubeSln/FairPlayTube.Models/CustomHttpResponse/ProblemHttpResponse.cs
  src/FairPlayTubeSln/FairPlayTube.Models/FairPlayTube.Models.csproj
  src/FairPlayTubeSln/FairPlayTube.Models/FairPlayTube.Models.xml
  src/FairPlayTubeSln/FairPlayTube.Models/Invites/InviteUserModel.cs
  src/FairPlayTubeSln/FairPlayTube.Models/Notifications/NotificationModel.cs
  src/FairPlayTubeSln/FairPlayTube.Models/Paypal/PaypalCheckoutApprovedDataModel.cs
  src/FairPlayTubeSln/FairPlayTube.Models/Paypal/PaypalCheckoutApprovedDetailsModel.cs
  src/FairPlayTubeSln/FairPlayTube.Models/Persons/PersonModel.cs
  src/FairPlayTubeSln/FairPlayTube.Models/UserMessage/UserMessageModel.cs
  src/FairPlayTubeSln/FairPlayTube.Models/UserProfile/GlobalMonetizationModel.cs
  src/FairPlayTubeSln/FairPlayTube.Models/UserProfile/UserModel.cs
  src/FairPlayTubeSln/FairPlayTube.Models/UserProfile/UserProfileModel.cs
  src/FairPlayTubeSln/FairPlayTube.Models/Video/GlobalKeywordModel.cs
  src/FairPlayTubeSln/FairPlayTube.Models/Video/UpdateVideoModel.cs
  src/FairPlayTubeSln/FairPlayTube.Models/Video/UploadVideoModel.cs
  src/FairPlayTubeSln/FairPlayTube.Models/Video/VideoInfoModel.cs
  src/FairPlayTubeSln/FairPlayTube.Models/Video/VideoJobModel.cs
  src/FairPlayTubeSln/FairPlayTube.Models/Video/VideoStatusModel.cs
  src/FairPlayTubeSln/FairPlayTube.Models/VisitorTracking/VisitorTrackingModel.cs
Labels: enhancement

#195 Enable server project documentation
  src/FairPlayTubeSln/FairPlayTube/AutoMapperProfiles/GlobalMappingProfile.cs
  src/FairPlayTubeSln/FairPlayTube/Controllers/AzureVideoIndexerController.cs
  src/FairPlayTubeSln/FairPlayTube/Controllers/UserController.cs
  src/FairPlayTubeSln/FairPlayTube/Controllers/UserProfileController.cs
  src/FairPlayTubeSln/FairPlayTube/Controllers/VideoController.cs
  src/FairPlayTubeSln/FairPlayTube/Controllers/VisitorTrackingController.cs
  src/FairPlayTubeSln/FairPlayTube/CustomProviders/CurrentUserProvider.cs
  src/FairPlayTubeSln/FairPlayTube/FairPlayTube.csproj
  src/FairPlayTubeSln/FairPlayTube/FairPlayTube.xml
  src/FairPlayTubeSln/FairPlayTube/Pages/Error.cshtml.cs
  src/FairPlayTubeSln/FairPlayTube/Program.cs
  src/FairPlayTubeSln/FairPlayTube/Startup.cs
  src/FairPlayTubeSln/FairPlayTube/Swagger/Filters/SecurityRequirementsOperationFilter.cs
Labels: enhancement

#197 Enabling language selection on upload
  src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Videos/Upload.razor
  src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Videos/Upload.razor.cs
  src/FairPlayTubeSln/FairPlayTube.Client/_Imports.razor
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/VideoInfo.cs
  src/FairPlayTubeSln/FairPlayTube.Database/FairPlayTube.Database.refactorlog
  src/FairPlayTubeSln/FairPlayTube.Database/dbo/Tables/VideoInfo.sql
  src/FairPlayTubeSln/FairPlayTube.Models/FairPlayTube.Models.xml
  src/FairPlayTubeSln/FairPlayTube.Models/Video/UploadVideoModel.cs
  src/FairPlayTubeSln/FairPlayTube.Models/Video/VideoInfoModel.cs
  src/FairPlayTubeSln/FairPlayTube.Services/BackgroundServices/VideoIndexStatusService.cs
  src/FairPlayTubeSln/FairPlayTube.Services/FairPlayTube.Services.csproj
  src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs
Labels: enhancement

#209 Adding video visibility table
  src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Videos/Upload.razor
  src/FairPlayTubeSln/FairPlayTube.Client/Pages/Users/Videos/Upload.razor.cs
  src/FairPlayTubeSln/FairPlayTube.Common/Global/Enums/VideoVisibility.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Data/FairplaytubeDatabaseContext.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/VideoInfo.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/VideoVisibility.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/efpt.config.json
  src/FairPlayTubeSln/FairPlayTube.Database/FairPlayTube.Database.refactorlog
  src/FairPlayTubeSln/FairPlayTube.Database/FairPlayTube.Database.sqlproj
  src/FairPlayTubeSln/FairPlayTube.Database/Scripts/PostDeployment/Script.PostDeployment.sql
  src/FairPlayTubeSln/FairPlayTube.Database/dbo/Tables/VideoInfo.sql
  src/FairPlayTubeSln/FairPlayTube.Database/dbo/Tables/VideoVisibility.sql
  src/FairPlayTubeSln/FairPlayTube.Models/FairPlayTube.Models.xml
  src/FairPlayTubeSln/FairPlayTube.Models/Video/UploadVideoModel.cs
  src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs
  src/FairPlayTubeSln/FairPlayTube/Controllers/VideoController.cs
Labels: enhancement

#213 Creating message service
  src/FairPlayTubeSln/FairPlayTube.Services/FairPlayTube.Services.csproj
  src/FairPlayTubeSln/FairPlayTube.Services/MessageService.cs
  src/FairPlayTubeSln/FairPlayTube/Controllers/UserController.cs
  src/FairPlayTubeSln/FairPlayTube/FairPlayTube.xml
  src/FairPlayTubeSln/FairPlayTube/Startup.cs
Labels: enhancement

#214 Adding services configuration
  src/FairPlayTubeSln/FairPlayTube/Startup.cs
Labels: enhancement

#216 Allow language detection on content moderation
  src/FairPlayTubeSln/FairPlayTube.Services/ContentModerationService.cs
  src/FairPlayTubeSln/FairPlayTube.Services/FairPlayTube.Services.csproj
  src/FairPlayTubeSln/FairPlayTube.Services/MessageService.cs
  src/FairPlayTubeSln/FairPlayTube/Startup.cs
Labels: enhancement

#219 Enabling Text Analysis Service
  src/FairPlayTubeSln/FairPlayTube.Services/FairPlayTube.Services.csproj
  src/FairPlayTubeSln/FairPlayTube.Services/TextAnalysisServices.cs
  src/FairPlayTubeSln/FairPlayTube/Startup.cs
Labels: enhancement

#220 Adding VideoCommentAnalysis table
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Data/FairplaytubeDatabaseContext.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/VideoComment.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/VideoCommentAnalysis.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/efpt.config.json
  src/FairPlayTubeSln/FairPlayTube.Database/FairPlayTube.Database.refactorlog
  src/FairPlayTubeSln/FairPlayTube.Database/FairPlayTube.Database.sqlproj
  src/FairPlayTubeSln/FairPlayTube.Database/dbo/Tables/VideoCommentAnalysis.sql
Labels: enhancement

#222 Adding "AnalyzeVideoCommentAsync" method.
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/VideoCommentAnalysis.cs
  src/FairPlayTubeSln/FairPlayTube.Database/dbo/Tables/VideoCommentAnalysis.sql
  src/FairPlayTubeSln/FairPlayTube.Services/TextAnalysisServices.cs
  src/FairPlayTubeSln/FairPlayTube.Services/VideoService.cs
Labels: enhancement

#224 Adding the "AnalyzeVideoComment" endpoint
  src/FairPlayTubeSln/FairPlayTube/Controllers/VideoController.cs
  src/FairPlayTubeSln/FairPlayTube/FairPlayTube.xml
Labels: enhancement

#226 Moving controller to an independent project
  src/FairPlayTubeSln/FairPlayTube.Controllers/AzureVideoIndexerController.cs
  src/FairPlayTubeSln/FairPlayTube.Controllers/FairPlayTube.Controllers.csproj
  src/FairPlayTubeSln/FairPlayTube.Controllers/FairPlayTube.Controllers.xml
  src/FairPlayTubeSln/FairPlayTube.Controllers/UserController.cs
  src/FairPlayTubeSln/FairPlayTube.Controllers/UserProfileController.cs
  src/FairPlayTubeSln/FairPlayTube.Controllers/VideoController.cs
  src/FairPlayTubeSln/FairPlayTube.Controllers/VisitorTrackingController.cs
  src/FairPlayTubeSln/FairPlayTube/FairPlayTube.csproj
  src/FairPlayTubeSln/FairPlayTube/FairPlayTube.xml
  src/FairPlayTubeSln/FairPlayTubeSln.sln
Labels: enhancement

#228 Adding the GatedFeature table
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Data/FairplaytubeDatabaseContext.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/Models/GatedFeature.cs
  src/FairPlayTubeSln/FairPlayTube.DataAccess/efpt.config.json
  src/FairPlayTubeSln/FairPlayTube.Database/FairPlayTube.Database.refactorlog
  src/FairPlayTubeSln/FairPlayTube.Database/FairPlayTube.Database.sqlproj
  src/FairPlayTubeSln/FairPlayTube.Database/dbo/Tables/GatedFeature.sql
Labels: enhancement

#230 Adding permissions config generator
  src/FairPlayTubeSln/FairPlayTube.SystemConfigurator/FairPlayTube.SystemConfigurator.csproj
  src/FairPlayTubeSln/FairPlayTube.SystemConfigurator/Pages/Index.razor
  src/FairPlayTubeSln/FairPlayTube.SystemConfigurator/Pages/Index.razor.cs
Labels: enhancement
